version: '3.8'
networks:
  cluster_demo:
    driver: bridge
services:
  mysql:
    networks:
      - cluster_demo
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    volumes:
      - "./resources/db.sql:/docker-entrypoint-initdb.d/db.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  resume:
    networks:
      - cluster_demo
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8002:8080"
    depends_on:
      mysql:
        condition: service_healthy